### ISSUE TITLE
Receipt PDFs

### ISSUE THREAD

**Issue by zombielinux** [GonzaloZiadi/CostcoWrapped#1]
So this is a cool project, but it involves going into costco's website to download their PDFs. 

Is there any flexibility to take a scanned/ocr'd image of the one given to you in store and doing a similar analysis?

My workflow is:

Checkout -> Scan with nextcloud app -> Feed into paperless-ngx -> Store forever. 

Ideally it would feed from the same nextcloud scan and into a database somewhere. Mostly to track prices over time. But other analysis would be awesome.

**Comment by GonzaloZiadi** [comment]
Hi William!

That sounds like an awesome idea, but I haven't had much time to work on this lately. If you want to send a PR I can review it and we can get it merged.

Thanks for reaching out :)

**Comment by bhattmayank** [comment]
Cool project, is there any possibility to bulk download all the receipts from its website or app?

**Comment by GonzaloZiadi** [comment]
Hello! It's not possible to bulk download as far as I know, unfortunately :(
